### ISSUE TITLE
Aspect ratio (wxh)changes from what entries in parameters.  

### ISSUE THREAD

**Issue by mcwaffle** [chigozienri/VQGAN-CLIP-animations#1]
It seems to adjust the aspect ratio slightly.  Examples below images output. Rendering produces the same resolution. 
Examples 

 
![image](https://user-images.githubusercontent.com/69012584/128789139-0aba085a-386a-4a24-95bd-51c96e83169d.png)

100x00
![100x100](https://user-images.githubusercontent.com/69012584/128789274-3ad49c20-0236-4e51-8504-18debe8a0cf6.png)
250x500
![250x500](https://user-images.githubusercontent.com/69012584/128789280-ec84c5a1-1ab3-4ff7-bb23-b2daffeca1aa.png)
333x666
![333x666](https://user-images.githubusercontent.com/69012584/128789281-6e561d35-2d8a-4304-82bc-53441fafc2fd.png)
400x700
![400x700](https://user-images.githubusercontent.com/69012584/128789282-9e2fe674-41ed-4387-a37b-a76ac4bb4223.png)
500x250
![500x250](https://user-images.githubusercontent.com/69012584/128789276-ad28ed6e-8803-4970-a66b-4bad5a7b009f.png)
500x500
![500x500](https://user-images.githubusercontent.com/69012584/128789277-b1454d2e-1b65-4031-892b-f1546c5c151f.png)
666x333
![666x333](https://user-images.githubusercontent.com/69012584/128789278-e725fb74-1044-4513-8ba3-dff0a9c2b497.png)
700x400
![700x400](https://user-images.githubusercontent.com/69012584/128789279-a358ea59-bb63-4765-a50f-f7497a4af2ff.png)

**Comment by chigozienri** [comment]
@mcwaffle Unfortunately this appears to be a fundamental limitation, the model uses multiples of 16.

**Comment by mcwaffle** [comment]
> @mcwaffle Unfortunately this appears to be a fundamental limitation, the model uses multiples of 16.

No thats good now, that in and of itself is a fix thanks.
