### ISSUE TITLE
Video cell error

### ISSUE THREAD

**Issue by Nil-Melius** [chigozienri/VQGAN-CLIP-animations#14]
Hi,

For some reason, I am receiving this error every time the "create video" cell tries to run. Everything works smoothly before that. What might be the reason?

<img width="1326" alt="Screenshot 2021-08-30 at 0 19 06" src="https://user-images.githubusercontent.com/89586905/131265737-9bc58f6a-36f6-41b9-8d27-9a6cd1bf28f9.png">

**Comment by Northloop** [comment]
I've been encountering this issue as well. I have all the steps in images, but I can't get it to collect the steps into a video. This is such an amazing colab that you've built, I would love to see this part working :)

**Comment by chigozienri** [comment]
Apologies for the delay, I've been away. I'll look into this.

**Comment by Northloop** [comment]
:) I also wanted to know if you have a place for donations. What you put together is amazing.

**Comment by chigozienri** [comment]
Could you run `print(stderr)` to get the whole traceback, and paste the results here?

I think this is another memory issue from doing a big run and then trying to make a video. If so, then if you kill the notebook (Runtime > Manage Sessions > Terminate), and then run just the google drive connection cell, the cell which defines the filepath, and the video cell, then it should work. Sorry for the annoying workaround, I might be able to make it a bit smoother if you can paste the traceback.

**Comment by Northloop** [comment]
I think you're on to something. I overused my alotted memory usage with colab and I'm paying for pro+ the image size I was working with was 405 x 720 and maybe I need cut that number down and upscale later. I'll give it another go when I get unbanned.

**Comment by therealjustlike** [comment]
Hello Chigozienri, 
When I am trying to use the super slo mo feature, Im not sure how to solve the error im getting in the attached screenshot. I have plugged in my file path where I thought it should go...but this is probably wrong. Can you spot my error and correct me? Appreciate the time and effort you have put into this! Thank you

![Screenshot_116](https://user-images.githubusercontent.com/2695255/134816112-7e8d4171-322f-4c5d-80ae-287e4fae9505.png)
I

**Comment by chigozienri** [comment]
@therealjustlike 
> Hello Chigozienri,
> When I am trying to use the super slo mo feature, Im not sure how to solve the error im getting in the attached screenshot. I have plugged in my file path where I thought it should go...but this is probably wrong. Can you spot my error and correct me? Appreciate the time and effort you have put into this! Thank you
> 
> ![Screenshot_116](https://user-images.githubusercontent.com/2695255/134816112-7e8d4171-322f-4c5d-80ae-287e4fae9505.png)
> I

I think you could just put a line `filepath=/content/HeiroGlyphs01.mp4` at the beginning of that cell (and revert the lines you have changed).

So overall, the cell should be:
```
filepath=/content/HeiroGlyphs01.mp4
SLOW_MOTION_FACTOR = 3#@param {type:"number"}
TARGET_FPS = 12#@param {type:"number"}

cmd1 = [
    'python',
    'Super-SloMo/video_to_slomo.py',
    '--checkpoint',
    pretrained_model,
    '--video',
    filepath,
    '--sf',
    str(SLOW_MOTION_FACTOR),
    '--fps',
    str(TARGET_FPS),
    '--output',
    f'{filepath}-slomo.mkv',
]
process = subprocess.Popen(cmd1, cwd=f'/content', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = process.communicate()
if process.returncode != 0:
    raise RuntimeError(stderr)

cmd2 = [
    'ffmpeg',
    '-i',
    f'{filepath}-slomo.mkv',
    '-pix_fmt',
    'yuv420p',
    '-crf',
    '17',
    '-preset',
    'veryslow',
    f'{filepath}-slomo.mp4',
]

process = subprocess.Popen(cmd2, cwd=f'/content', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdout, stderr = process.communicate()
if process.returncode != 0:
    raise RuntimeError(stderr)
    print(stderr)
    print(
        "You may be able to avoid this error by backing up the frames,
        "restarting the notebook, and running only the video synthesis cells,"
        "or by decreasing the resolution of the image generation steps. "
        "If not, please post the traceback in the github.")
```

**Comment by therealjustlike** [comment]
Hi! That moved the needle a bit...but now I get this.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-81630615491e> in <module>()
     17     f'{filepath}-slomo.mkv',
     18 ]
---> 19 process = subprocess.Popen(cmd1, cwd=f'/content', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     20 stdout, stderr = process.communicate()
     21 if process.returncode != 0:

NameError: name 'subprocess' is not defined

**Comment by chigozienri** [comment]
> Hi! That moved the needle a bit...but now I get this.
> 
> NameError Traceback (most recent call last)
> in ()
> 17 f'{filepath}-slomo.mkv',
> 18 ]
> ---> 19 process = subprocess.Popen(cmd1, cwd=f'/content', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> 20 stdout, stderr = process.communicate()
> 21 if process.returncode != 0:
> 
> NameError: name 'subprocess' is not defined

I have added `import subprocess` to the beginning of all the video generation cells, for when they are run without running the setup cells at the start. Try again now?

**Comment by chigozienri** [comment]
> :) I also wanted to know if you have a place for donations. What you put together is amazing.

Thanks, that's so kind! For now, if you would like to, you can donate to the https://www.givewell.org/maximum-impact-fund on my behalf, as this is just a side project and I don't feel it is polished enough to ask for payment. However, if I put more time into adding features, increasing the ease-of-use and helping users, would you want me to start a patreon/ko-fi/that sort of thing?

**Comment by therealjustlike** [comment]
> > :) I also wanted to know if you have a place for donations. What you put together is amazing.
> 
> Thanks, that's so kind! For now, if you would like to, you can donate to the https://www.givewell.org/maximum-impact-fund on my behalf, as this is just a side project and I don't feel it is polished enough to ask for payment. However, if I put more time into adding features, increasing the ease-of-use and helping users, would you want me to start a patreon/ko-fi/that sort of thing?

I will donate and subscribe to your patreon, thank you for your help!

**Comment by therealjustlike** [comment]
> @therealjustlike
> 
> > Hi! That moved the needle a bit...but now I get this.
> > NameError Traceback (most recent call last)
> > in ()
> > 17 f'{filepath}-slomo.mkv',
> > 18 ]
> > ---> 19 process = subprocess.Popen(cmd1, cwd=f'/content', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> > 20 stdout, stderr = process.communicate()
> > 21 if process.returncode != 0:
> > NameError: name 'subprocess' is not defined
> 
> I have added `import subprocess` to the beginning of all the video generation cells, for when they are run without running the setup cells at the start. Try again now?

I think its working now!
I found a tiny missing " at the end of this line...
"You may be able to avoid this error by backing up the frames,"

**Comment by therealjustlike** [comment]
Hi
It worked and then on 2nd try got this error

RuntimeError                              Traceback (most recent call last)
<ipython-input-25-f72a38d96233> in <module>()
     40 stdout, stderr = process.communicate()
     41 if process.returncode != 0:
---> 42     raise RuntimeError(stderr)
     43     print(stderr)
     44     print(

RuntimeError: b"ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 78.100 / 55. 78.100\n  libavcodec     57.107.100 / 57.107.100\n  libavformat    57. 83.100 / 57. 83.100\n  libavdevice    57. 10.100 / 57. 10.100\n  libavfilter     6.107.100 /  6.107.100\n  libavresample   3.  7.  0 /  3...

**Comment by chigozienri** [comment]
> > @therealjustlike
> > > Hi! That moved the needle a bit...but now I get this.
> > > NameError Traceback (most recent call last)
> > > in ()
> > > 17 f'{filepath}-slomo.mkv',
> > > 18 ]
> > > ---> 19 process = subprocess.Popen(cmd1, cwd=f'/content', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> > > 20 stdout, stderr = process.communicate()
> > > 21 if process.returncode != 0:
> > > NameError: name 'subprocess' is not defined
> > 
> > 
> > I have added `import subprocess` to the beginning of all the video generation cells, for when they are run without running the setup cells at the start. Try again now?
> 
> I think its working now!
> I found a tiny missing " at the end of this line...
> "You may be able to avoid this error by backing up the frames,"

@therealjustlike Thanks, I just found it too :p

**Comment by chigozienri** [comment]
> Hi
> It worked and then on 2nd try got this error
> 
> RuntimeError Traceback (most recent call last)
> in ()
> 40 stdout, stderr = process.communicate()
> 41 if process.returncode != 0:
> ---> 42 raise RuntimeError(stderr)
> 43 print(stderr)
> 44 print(
> 
> RuntimeError: b"ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers\n built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n libavutil 55. 78.100 / 55. 78.100\n libavcodec 57.107.100 / 57.107.100\n libavformat 57. 83.100 / 57. 83.100\n libavdevice 57. 10.100 / 57. 10.100\n libavfilter 6.107.100 / 6.107.100\n libavresample 3. 7. 0 / 3...

I can't see the end of the traceback, but this seems like a memory issue again, try completely killing the runtime (Runtime > Manage sessions > Terminate, rather than just Runtime > Factory reset runtime). Sorry, I can't really do much about google colab's limits, only try to work around them.
