### ISSUE TITLE
NameError: name 'working_dir' is not defined

### ISSUE THREAD

**Issue by anemone1368** [chigozienri/VQGAN-CLIP-animations#15]
hi I get this error constantly,
could you please help me what is the problem?

**Comment by Atmannen** [comment]
Either you have not connected google drive to the notebook. Or you have not uncommented block 2 where it says to uncomment.
`If you choose not to use google drive, uncomment the cell below and run it instead.
# working_dir = '/content'`

**Comment by chigozienri** [comment]
Thanks, @Atmannen is correct.
