### ISSUE TITLE
cannot generate video

### ISSUE THREAD

**Issue by cjohns7777** [chigozienri/VQGAN-CLIP-animations#21]
**Describe the bug**
In trying to generate a video i keep getting a runtime error. 

**Parameters used**
Paste in the parameters you used
Dont have all this info any longer but resolution was 400x400

**Which cell you saw the error in**
Make a video of the results

**Error message**
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-52199fda6b03> in <module>()
     44 stdout, stderr = process.communicate()
     45 if process.returncode != 0:
---> 46     raise RuntimeError(stderr)
     47     print(stderr)
     48     print(

RuntimeError: b"ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers\n  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)\n  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared\n  libavutil      55. 78.100 / 55. 78.100\n  libavcodec     57.107.100 / 57.107.100\n  libavformat    57. 83.100 / 57. 83.100\n  libavdevice    57. 10.100 / 57. 10.100\n  libavfilter     6.107.100 /  6.107.100\n  libavresample   3.  7.  0 /  3...
![Screen Shot 2021-10-01 at 1 12 46 PM](https://user-images.githubusercontent.com/91754679/135667686-a3134e69-9837-47ee-9f0a-e68fffaeafa1.jpg)
![Screen Shot 2021-10-01 at 1 12 26 PM](https://user-images.githubusercontent.com/91754679/135667694-c943f320-0d1b-4bb8-af7b-9d042a4cac07.jpg)

**Screenshots**

**Additional context**
I have attempted to terminate and restart. Pardon my ignorance in this. Just learning. I was able to create a video on my first pass but ever since I have encountered issues. Also, I am on Colab pro plus.

**Comment by tomfpritchard** [comment]
@cjohns7777 have you tried clearing your old outputs from the working directory? I had this problem and I think it may have been caused by ffmpeg not having permission to overwrite files. Not 100% sure that's the cause of the problem but it's worth a try.

**Comment by chigozienri** [comment]
Sorry it took me a while to get to this.

If you run again, you should be able to see the full error message, which might help in diagnosing.

However, I suspect that it is an out-of-memory issue (though that's concerning if you are on Colab Pro Plus). If that's the case, you may be able to avoid this error by backing up the frames, restarting the notebook (completely - go to "Runtime>Manage Sessions>Terminate"), re-uploading the frames, and then running only the video synthesis cells. You will also have to define the `filepath` manually by running `filepath = 'PATH_TO_THE_VIDEO'`.

**Comment by tomfpritchard** [comment]
I think you may be right. I ran the notebook today with an A100 and didn't get the same error, despite getting it most of the time before. I'd taken to running the slomo section in a separate notebook because it errors too often.

Regarding the A100 though, it was horrifically slow. I heard you can get OpenAI Jukebox to run quite well on it by using later CUDA versions, but I tried their fix on this notebook and it was still snail paced. Do you know how we can mod this to fully utilize the new GPU?
