### ISSUE TITLE
A100 Support

### ISSUE THREAD

**Issue by rs3dtouch** [chigozienri/VQGAN-CLIP-animations#29]
When using a A100 (Pro+) the processing is dramatically slow, several times slower than a P100/V100.

This is probably an issue with one of the libraries, but I could not figure out which one.

Any comments appreciated, thank you very much.

**Comment by chigozienri** [comment]
Thanks for the report. This is quite difficult for me to test myself, as I don't have Colab Pro+. I could try to do a troubleshooting call with you, if that works?

**Comment by chigozienri** [comment]
For now, I've added a recommendation to reload until you get a V100 or P100, and I'm closing this issue. If I get an opportunity to test on a Colab Pro account I can re-open it.

**Comment by chigozienri** [comment]
@rs3dtouch or @tomfpritchard I might have a fix, could you try running
`torch.backends.cudnn.enabled = False` after the 'installation and loading of libraries' step?

**Comment by chigozienri** [comment]
I've pushed a possible fix, but have no way to test. If I get more reports, I'll re-open the issue.
