### ISSUE TITLE
the working_dir tab is gone and I cannot actually do the run

### ISSUE THREAD

**Issue by frankyakabigmac** [chigozienri/VQGAN-CLIP-animations#31]
**Describe the bug**

**Parameters used**
Paste in the parameters you used
e.g.
key_frames = True #@param {type:"boolean"}
text_prompts = "10:(Apple: 1| Orange: 0), 20: (Apple: 0| Orange: 1| Peach: 1)" #@param {type:"string"}
width =  400#@param {type:"number"}
height =  400#@param {type:"number"}
model = "vqgan_imagenet_f16_16384" #@param ["vqgan_imagenet_f16_16384", "vqgan_imagenet_f16_1024", "wikiart_16384", "coco", "faceshq", "sflckr"]
interval =  1#@param {type:"number"}
initial_image = ""#@param {type:"string"}
target_images = ""#@param {type:"string"}
seed = 1#@param {type:"number"}
max_frames = 50#@param {type:"number"}
angle = "10: (0), 30: (10), 50: (0)"#@param {type:"string"}
zoom = "10: (1), 30: (1.2), 50: (1)"#@param {type:"string"}
translation_x = "0: (0)"#@param {type:"string"}
translation_y = "0: (0)"#@param {type:"string"}
iterations_per_frame = "0: (10)"#@param {type:"string"}
save_all_iterations = False#@param {type:"boolean"}

**Which cell you saw the error in**
e.g. "Actually do the run"

**Error message**
Paste in the traceback you saw

**Screenshots**

**Additional context**
Add any other context about the problem here. e.g. Had you restarted to use only the video generation cells? Are you using google drive?

**Comment by chigozienri** [comment]
If you don't want to use google drive, uncheck the google_drive checkbox in the "Run me: Google drive connection" cell
You still need to run the cell.

You also need to run the cell "Run me (Add inbetweens to parameters)" (even if you didn't run the visual editor cells).

Closing for now, if you still have problems you can re-open or make another issue.
