### ISSUE TITLE
Cant input last video path into new Resolution Increase

### ISSUE THREAD

**Issue by AM137** [chigozienri/VQGAN-CLIP-animations#33]
Getting an error when trying to import a video manually on the SRCNN session.
**Parameters used**
filename ='/content/video(7).mp4'

**Error message**
RuntimeError                              Traceback (most recent call last)

**Screenshots**
![troublshoot w google colab 1](https://user-images.githubusercontent.com/99808886/154266687-66e5d4ae-0f63-406f-a29c-97f11508ff1b.PNG)

**Comment by chigozienri** [comment]
The SCRNN cell is designed to work with frames, not assembled videos. Try using the notebook at https://github.com/sadnow/AnimationKit-AI for what you want to do, instead!
