### ISSUE TITLE
 'int' object has no attribute 'backwards'

### ISSUE THREAD

**Issue by tomatopuree** [chigozienri/VQGAN-CLIP-animations#8]
I am getting this error: 'int' object has no attribute 'backwards'

I am running with google drive integration and with sflckr.

I did run everything in order.

![image](https://user-images.githubusercontent.com/688831/130293569-812ef66d-2a93-43fa-8f56-231e29c9e73e.png)

**Comment by chigozienri** [comment]
Hi @tomatopuree 
You need to use at least one text prompt or image prompt, otherwise you will see this error. If you are using a prompt, please paste the parameters you are using below. Thanks!

**Comment by tomatopuree** [comment]
These are my inputs. There is a text prompt.

![image](https://user-images.githubusercontent.com/688831/130339170-9c7b8c94-e2ec-4461-a9f4-40ef3f114d04.png)

**Comment by tomatopuree** [comment]
Solved by entering prompt in this format

0:(Prompt text: 1)

**Comment by chigozienri** [comment]
Thanks for sending the parameters, I'll update with a warning if `key_frames` is ticked and the prompts aren't in that format.
