### ISSUE TITLE
Blurry images generated when i != 0

### ISSUE THREAD

**Issue by tomatopuree** [chigozienri/VQGAN-CLIP-animations#9]
The execution works but it produces blurry images after the first iteration.

Parameters:
![image](https://user-images.githubusercontent.com/688831/130365700-b30f8c7f-2eb4-46ae-8164-ff380bc5505d.png)

Example of issue:
![image](https://user-images.githubusercontent.com/688831/130365734-3a28e0a4-0c94-446f-9a8e-32c11d0020f2.png)

For any prompt, it does that. The images after the very first one are always completely blurry. What might be the cause of this?

**Comment by chigozienri** [comment]
Zoom needs to be 1, not 0, for no zoom to happen. A zoom of 0 zooms out infinitely. It's described in the "instructions for setting parameters" section, but I could try to make it clearer, or put a warning if users try to use a zoom of 0.

**Comment by tomatopuree** [comment]
You are right! My bad. Thank you for your time!

Speaking for myself, it was definitely easy to miss. I personally would have benefitted of a mention of this not in the parameters table but in the "Transformations (zoom, rotation, and translation)" subheading, since I've skimmed the parameters given that they are mostly self explanatory, and looked for mention of more subtle implementation details in the paragraphs under the table.
